matrix-nio/matrix-nio

nio/api.py, nio/client.py, nio/responses.py
As per https://matrix.org/docs/spec/client_server/r0.4.0.html#put-matrix-client-r0-profile-userid-displayname
I am not yet familiar with codebase, so please tell me if I forgot something.
=> profile set displayname API added

nio/rooms.py, tests/room_test.py
- implemented disambiguated display name as per https://matrix.org/docs/spec/client_server/r0.4.0.html#id346
- such display name used for room name derivation
=> user name disambiguation implemented for room names

nio/events.py, nio/rooms.py, nio/schemas.py, tests/data/events/guest_access.json, tests/data/events/history_visibility.json, tests/data/events/join_rules.json, tests/event_test.py, tests/room_test.py
Following #11 
https://matrix.org/docs/spec/client_server/latest.html#m-room-guest-access
https://matrix.org/docs/spec/client_server/latest.html#m-room-join-rules
https://matrix.org/docs/spec/client_server/latest.html#m-room-history-visibility
=> Support for all room initial events

nio/api.py, nio/client/base_client.py, nio/client/http_client.py, nio/responses.py, nio/store/database.py, tests/client_test.py, tests/store_test.py
https://matrix.org/docs/spec/client_server/latest.html#post-matrix-client-r0-rooms-roomid-forget
=> Add forget room API

nio/client/async_client.py, nio/client/http_client.py, nio/responses.py, tests/async_client_test.py, tests/data/room_id.json, tests/responses_test.py
Also adds some missing `HttpClient` docstrings and response tests.
=> Add room join, leave and forget methods for async client

.gitignore, nio/events/account_data.py, nio/schemas.py, tests/data/events/tag.json, tests/event_test.py
New try. I had many problems with the rebasing (need to play around before using it on github/gitlab, sorry).
This is a complete new version with better TagEvent description, better schema for tags, test via AccountDataEvent.parse_event.
=> m.tag implementation

nio/client/async_client.py
=> add missing call for storing sync token

README.md
This minor PR adds two commas.
I think it's easier to understand the sentences.
=> Add commas to read easily README file

README.md
It took me a bit to figure out how to send a message so I figured I'd add a quick example.
Let me know if I missed something.
=> Add example for sending message

nio/client/base_client.py
=> Add missing raise keyword

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py, tests/data/room_state.json
- resolve room aliases
- fetch joined\_rooms
- fix room creation when using aliases
- fix a typo in the test cases
- a bunch of improvements for sending/fetching state
=> Various improvements

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py
Provides a way to know the maximum upload file size on the server: https://matrix.org/docs/spec/client_server/latest#get-matrix-media-r0-config
=> Add server content repository config API

nio/client/async_client.py
...as implemented for http_client. This is needed for clients which
re-connect with an existing session.
=> Implement async_client login with token option

nio/api.py, nio/client/async_client.py, nio/responses.py, tests/async_client_test.py
https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-rooms-roomid-ban
https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-rooms-roomid-unban
=> Ban/unban support in Api and AsyncClient

nio/client/async_client.py
Disable the client timeout for `AsyncClient.sync()` if the `full_state` argument is true, and for the first sync in `AsyncClient.sync_forever()`.
This is to prevent heavy syncs with large accounts from constantly getting timed out before the server can return anything.
=> Disable timeout for initial sync or full_state sync

nio/api.py, nio/client/async_client.py, nio/client/base_client.py, nio/events/to_device.py
Hello,
this pull-request documents which functions are automatically-called, which are low-level and fixes a few minor details.
I'm not 100% sure if the following comment for send() is true: "This function does not call receive_response()." Please check this before merging the commit.
Regards
Simon
=> Documentation updates

nio/client/async_client.py, tests/async_client_test.py
A middleman between us and the server like Cloudflare can return
HTTP responses with the 429 status ("Too many requests"), before our
request reaches the matrix server for it to return a proper JSON
response with the `M_LIMIT_EXCEEDED` code.
=> AsyncClient: catch transport response 429 errors

README.md, doc/built-with-nio.rst, doc/conf.py, doc/contributing.rst, doc/examples.rst, doc/index.rst, doc/nio.rst, examples/basic_client.py, examples/manual_encrypted_verify.py, examples/restore_login.py, rtd-requirements.txt
Closes #104
This one will probably take a while to review; I would really appreciate a slow and careful read through all of the examples, the new pages, and all the comments. If you can, running the example programs yourself and making sure they work would be 💯
More eyes are better as far as I'm concerned
I've seen lots of confusion about how to use nio, and I hope to clear that up by starting a page of examples for folks to work from. Ideally it can be the "nio best practices" page, although I'm not sure we're there yet. I'm especially concerned about the encryption example; I've never used it before writing the program and I worry that I've missed critical explanations that would make nio clear
The contribution guide I wrote because I found it a little daunting to get started myself; …
=> Add feature list, examples, and contribution guide

CHANGELOG.md
And also make the blank lines after titles consistent
=> Update changelog for v0.13.0

nio/http.py
=> Add h2 config

examples/manual_encrypted_verify.py
Apparently I done goofed. Don't worry, I've changed the password already.
=> Remove my bots password 😞

examples/restore_login.py
- why? useful because users will see it later in their other apps
- why? good practice maybe?
- just 2 extra lines of code
=> added device_name

examples/send_image.py
- it is 1-to-1 identical to restore_login.py, users using it don't even have to enter homeserver, password, etc. again
- just 1 function is new: showing how to send an image (jpg, png, gif, svg, etc.)
- the suggestion is that the person learning, uses this after he has used restore_login.py, but any ordering will work
- program works out of the box, as-is, person can download it and run it right away without changing source code
=> example of how to send an image (jpg, gif, png...)

doc/examples.rst
=> added Emoji Verification to documentation

examples/verify_with_emoji.py
- for full description please read the first page of the source code
- can be run as-is, out-of-the-box, batteries-included
- no source code change needed to run and verify with someone
=> sample program showing how to do Emoji Verification with matrix-nio SDK

examples/README.md
- it does not need to have much text
- I wanted to cover just 2 issues:
- there is an ORDER to the examples, people should KNOW about this 
ORDER and go thru the examples in the correct ORDER
- animate people to play with the examples
=> readme for examples

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py
https://matrix.org/docs/spec/client_server/latest#well-known-uri
=> Add discovery info (.well-known) support

nio/client/async_client.py, nio/client/base_client.py, nio/responses.py
=> Generate a RoomGetStateEventError class when a 404 is returned

nio/crypto/olm_machine.py
Fixes https://github.com/matrix-org/pantalaimon/issues/73.
=> crypto: Copy over the relates_to dict when decrypting.

pyproject.toml
=> nio: Upgrade our deps

nio/events/room_events.py
=> events: Fix StickerEvent parsing

nio/api.py
In the current version of the library, it is only possible to use the Matrix ID as username. For some servers, this seems to be a problem.
This PR changes the main `Api.login` method to auto-detect email addresses as usernames: a username is an email address if it contains an `@` and no `:`.
If this PR is merged, it would also be nice to update `weechat-matrix` to depend on the updated version of this library :)
=> Login: support using email as username

nio/client/async_client.py, nio/client/base_client.py
This is very helpful if the homeserver has custom headers
=> Add custom headers option to client

nio/client/base_client.py
=> Fix type annotation for async callbacks in add_event_callback()

nio/api.py, nio/client/async_client.py, nio/events/room_events.py, nio/responses.py, nio/rooms.py, nio/schemas.py, tests/api_test.py, tests/room_test.py
ref: https://github.com/poljar/matrix-nio/issues/47
=> Add support for room upgrades

nio/api.py, nio/client/async_client.py, nio/responses.py, tests/async_client_test.py
When passing in `space=True` to `room_create`, a Space will be created.
This is a part of the Matrix 1.2 C2S API spec coming out soon.
Refs: #295
=> Allow creating spaces

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py
=> Add functionality for fetching OpenID access token

nio/client/async_client.py
=> small mistake in the documentation

doc/examples.rst
Minor formatting fix that fixes a list inside the examples documentation
=> Formatting fix

nio/client/base_client.py
=> wich -> which

nio/schemas.py
Ref: https://spec.matrix.org/v1.3/client-server-api/#knocking-on-rooms
=> Add `restricted` and `knock_restricted` join rules to schema.

nio/_compat.py, tests/async_attachment_test.py, tests/async_client_test.py, tests/conftest_async.py
- tests: Fix our async tests
- chore: Remove the usage of the imp module
=> Fix the async tests

examples/basic_client.py, examples/restore_login.py, examples/send_image.py, examples/verify_with_emoji.py
Closes https://github.com/poljar/matrix-nio/issues/302
=> fix deprecation warning in examples

doc/built-with-nio.rst
I spent a little time this morning looking at projects. I found opsdroid, and have added it. It's also helpful to have descriptions when doing this, so I added some descriptions.
=> Add content to built-with-nio

CHANGELOG.md, contrib/archlinux/pkgbuild/PKGBUILD.git, doc/conf.py, pyproject.toml
Modeled from this commit: https://github.com/poljar/matrix-nio/commit/17ef718fe3feda28fe79efea7edba9381a11b6ea
=> chore: Bump the version

nio/client/async_client.py, nio/client/base_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py, tests/data/whoami_response.json
Matrix Spec: https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv3accountwhoami
=> Bugfix: make WhoamiResponse alter async_client state appropriately.

nio/client/async_client.py, nio/client/base_client.py, tests/async_client_test.py, tests/client_test.py
=> Revert "Fixed bug in Event Callbacks"

nio/client/base_client.py
=> Fix ImportError from when e2e is not installed

nio/client/base_client.py, nio/event_builders/event_builder.py, nio/events/to_device.py, nio/responses.py, tests/data/events/unknown.json, tests/data/events/unknown_to_device.json, tests/event_test.py
=> Allow custom `ToDeviceEvent`s via `UnknownToDeviceEvent`

nio/client/async_client.py, nio/client/base_client.py, tests/async_client_test.py
=> Remove callback execution boilerplate + allow arbitrary callable/awaitable objects.

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, tests/api_test.py, tests/async_client_test.py, tests/conftest.py, tests/conftest_async.py
https://github.com/matrix-org/matrix-doc/pull/2844
Fixes #485
=> Spec: Compliance with MSC2844

doc/built-with-nio.rst
Added project bartleby to built-with-nio documentation page. Bartleby is an LLM chatbot and writing assistant written in python using HuggingFace transformers and matrix-nio. It also supports Discord. The project goals are:
1. Be open source and use open source models
2. Allow as much user configurability and tweaking as possible via the chat interface
3. Make and upload documents to google drive like a human collaborator would
Bartleby was just named a finalist in the Backdrop Build V3 build challenge.
=> Add bartleby to built-with-nio

nio/events/room_events.py, nio/rooms.py, nio/schemas.py, tests/data/context.json, tests/data/events/create.json, tests/data/events/create_typed.json, tests/data/room_state.json, tests/data/sync.json, tests/room_test.py
This closes https://github.com/matrix-nio/matrix-nio/issues/477
=> feat: remove creator property in event

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py, tests/data/list_public_rooms.json
=> Add AsyncClient.list_public_rooms
