nio/events.py, nio/rooms.py, tests/room_test.py
We need this because we prefix named rooms with '#', even if we are
using the room name and not the canonical alias (unlike Riot).
=> If the room display name already starts with a '#', don't add another one.

nio/events.py, nio/rooms.py, nio/schemas.py, tests/data/events/create.json, tests/event_test.py, tests/room_test.py
https://matrix.org/docs/spec/client_server/latest.html#m-room-create
Some standard events when a room is created (`m.room.create`, `m.room.join_rules`, `m.room.history_visibility`, `m.room.guest_access`) are returned as `UnknownEvent`.
I plan to add support for them, please tell me if I did any mistake.
=> Support for room creation event

nio/api.py, nio/client/http_client.py, nio/responses.py, nio/schemas.py, tests/data/get_displayname_response.json, tests/responses_test.py
https://matrix.org/docs/spec/client_server/latest.html#get-matrix-client-r0-profile-userid-displayname
There currently is no way to get our own display name if we haven't joined any room, or the name of another user that doesn't share any room with us.
=> Add profile get displayname API

nio/api.py, nio/client/base_client.py, nio/client/http_client.py, nio/responses.py, nio/rooms.py, nio/schemas.py, tests/client_test.py, tests/data/get_avatar_response.json, tests/helpers.py, tests/responses_test.py, tests/room_test.py
This adds support for avatars in `MatrixRoom`, `MatrixUser`, and the [get](https://matrix.org/docs/spec/client_server/latest.html#get-matrix-client-r0-profile-userid-avatar-url)/[set](https://matrix.org/docs/spec/client_server/latest.html#put-matrix-client-r0-profile-userid-avatar-url) avatar API.
=> Add avatars support

nio/events/invite_events.py, nio/events/room_events.py, nio/schemas.py
On my homeserver, removing a room alias results in an event with an empty content object, like so:
```json
{
"origin_server_ts": 1532312562923,
"sender": "@[redacted]",
"event_id": "$[redacted]",
"unsigned": {
"prev_content": {"alias": "#[redacted]"},
"prev_sender": "@[redacted]",
"replaces_state": "$[redacted]",
"age": 27083364217
},
"state_key": "",
"content": {},
"type": "m.room.canonical_alias"
}
```
[From the specification](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-room-canonical-alias):
> A room with an `m.room.canonical_alias` event with an absent, null, or empty `alias` field should be treated the same as a room with no `m.room.canonical_alias` event.
=> Handle m.room.canonical_alias with absent alias

nio/client/base_client.py
Typo in method name: ephermeral -> ephemeral. This patch renames to add_ephemeral_callback. The original method then warns that it is deprecated and then calls add_ephemeral_callback
=> method has typo: add_ephermeral_callback -> add_ephemeral_callback

.gitignore, nio/events/room_events.py, nio/rooms.py, nio/schemas.py, tests/data/events/room_avatar.json, tests/event_test.py
- `test_room_avatar_event`
- `room_avatar` schema for testing
- `RoomAvatarEvent`
- interpret `m.room.avatar` and set `room_avatar_url` in `MatrixRoom`
- additional `gen_avatar_url` for calculating the `avatar_url` on all rooms including grouped rooms
=> Room avatar url

nio/client/async_client.py
`AsyncClient`'s `sync_forever` can still exit due to `asyncio.TimeoutError`, which is not a subclass of the standard `TimeoutError`:
```py3
File "matrix-nio/nio/client/async_client.py", line 371, in sync_forever
await self.sync(timeout, sync_filter, since, full_state)
File "matrix-nio/nio/client/async_client.py", line 300, in sync
response = await self._send(SyncResponse, method, path)
File "matrix-nio/nio/client/async_client.py", line 200, in _send
transport_response = await self.send(method, path, data)
File "matrix-nio/nio/client/async_client.py", line 69, in wrapper
return await func(self, *args, **kwargs)
File "matrix-nio/nio/client/async_client.py", line 238, in send
headers=headers
File ".local/lib/python3.6/site-packages/aiohttp/client.py", line 499, in _request
await …
```
=> Also catch asyncio.TimeoutError in sync_forever

nio/schemas.py
It turns out the `displayname` or `avatar_url` can be missing from the response.
=> Fix get_profile schema

nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py, tests/data/limit_exceeded_error.json, tests/responses_test.py
This adds a `LimitExceededError` class for this kind of response:
```json
{
"errcode": "M_LIMIT_EXCEEDED",
"error": "Too many requests",
"retry_after_ms": 2000
}
```
and makes `AsyncClient._send` retry when getting this error response, after sleeping for the given time.
I wrote a test for the response, but I'm not too sure of how to write one for the `_send`. Can I get some indications, if this test is needed?
=> Handling limit exceeded errors in async client

nio/__init__.py, nio/rooms.py
For conveniance and consistency, since everything else is already available at root level. This avoids having to do:
```py
import nio
from nio.rooms import MatrixRoom, MatrixUser
```
=> Import rooms module classes at root level

nio/rooms.py
When a profile changed, `handle_membership` returned right after setting a new display name, before being able to set a new avatar.
=> Fix MatrixRoom profile change handling

nio/rooms.py
When a named room contains exactly two users and has no avatar set, Riot shows the avatar of the user that's not ourselves. This improves `MatrixRoom.gen_avatar_url` to behave like this.
=> Return an avatar for two users rooms

README.md, nio/client/async_client.py
- Use `asyncio.ensure_future()` instead of `asyncio.create_task()`, the former is an equivalent available in earlier Python versions
- Make the README example work for Python 3.5+
- Add missing punctuation in the README to make it easier to read
Many people don't have access to 3.7 in their distro yet, I'm stuck on 3.6 myself.
=> Python <3.7 and README fixes

nio/api.py, nio/client/async_client.py, tests/async_client_test.py
https://matrix.org/docs/spec/client_server/latest#post-matrix-media-r0-upload
After your https://github.com/poljar/matrix-nio/pull/39#issuecomment-510170310, I looked into the aiohttp docs and found that it accepts a file-like object or async generator as data for a request (see [this](https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-uploads)).
I made `upload()` accept bytes or such objects, and added a `content_type` argument to `_send()`.
I haven't implemented the method for `HttpClient` (yet?), since I don't use it anymore and it requires more complicated changes to `_build_request()` and `HttpRequest`. Can this be merged like this?
=> Add upload method to async client

nio/client/__init__.py, nio/client/async_client.py, nio/client/base_client.py, nio/events/to_device.py, nio/responses.py, tests/async_client_test.py
This adds handling of `ClientConnectionError`, `TimeoutError` and `asyncio.TimeoutError` for all async client requests instead of just inside `sync_forever()`.
I added an `AsyncClientConfig` that allows setting the max timeouts before raising, max limit exceeded errors before retuning an `ErrorResponse`, an exponential backoff factor to control the wait time between retries (inspired from [urllib](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.retry.Retry)), and a max total wait time.
Additionally, in `sync_forever()`: `sync()`, `send_to_device_messages()`, `keys_upload()` and `keys_query()` 
will now be run concurrently instead of waiting for each others, thus reducing initial delays with E2E rooms.
=> Async timeouts handling

nio/client/async_client.py, nio/client/http_client.py, tests/async_client_test.py
If the returned content-type of the response is `application/json`, the body must be parsed as such instead of being passed as bytes.
=> Fix FileResponse error parsing

nio/client/async_client.py, nio/client/base_client.py
Joined room events are handled by nio before calling user-registered callbacks. It should be the same for invited rooms, else the callback will receive an outdated `MatrixInvitedRoom`.
=> Handle invited events before calling callbacks

nio/crypto/olm_machine.py, nio/exceptions.py
#61 
Decided to subclass because `OlmTrustError` doesn't always mean unverified devices afaict.
=> Expose unverified devices in errors

nio/__init__.py, nio/api.py, nio/client/async_client.py, nio/client/http_client.py, nio/responses.py, tests/async_client_test.py, tests/client_test.py, tests/responses_test.py
This adds support for the [createRoom API](https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-createroom), with the exception of the `invite_3pid` key.
=> Add createRoom API 

nio/__init__.py, nio/client/async_client.py, nio/client/base_client.py, nio/client/http_client.py, nio/crypto/sas.py, nio/crypto/sessions.py, nio/event_builders/__init__.py, nio/event_builders/direct_messages.py, nio/event_builders/state_events.py, nio/events/room_events.py, tests/client_test.py, tests/event_builders_test.py
This adds a new `event_builders` subpackage for classes that help easily creating event dicts to use for `room_create()` or `room_send()`. 
The already existing helper class `ToDeviceMessage` has been moved to the `nio.event_builders.direct_messages` module.
Included is a new `EnableEncryptionBuilder` class under the `nio.event_builders.state_events` module, to build [`m.room.encryption`](https://matrix.org/docs/spec/client_server/latest#m-room-encryption) events.
=> Add event builders

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, nio/responses.py, tests/async_client_test.py, tests/client_test.py, tests/responses_test.py
This adds support in the http and async clients for the two download API: [normal](https://matrix.org/docs/spec/client_server/latest#get-matrix-media-r0-download-servername-mediaid) and [with filename](https://matrix.org/docs/spec/client_server/latest#get-matrix-media-r0-download-servername-mediaid-filename).
=> Add download API

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, tests/async_client_test.py, tests/client_test.py
The GET [profile](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-profile-userid), [displayname](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-profile-userid-displayname) and [avatar](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-profile-userid-avatar-url) API don't require to be logged in.
=> Allow getting profile/name/avatar without login

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, tests/async_client_test.py, tests/client_test.py
Like the download API, the [thumbnail API](https://matrix.org/docs/spec/client_server/latest#get-matrix-media-r0-thumbnail-servername-mediaid) doesn't require us to be logged in.
=> Allow using thumbnails API without logging in

nio/client/async_client.py, nio/crypto/__init__.py, nio/crypto/async_attachments.py, nio/crypto/attachments.py, rtd-requirements.txt, setup.py, tests/async_attachment_test.py, tests/async_client_test.py, tests/data/test_bytes
- Added `nio.crypto.attachments.encrypted_attachment_generator()`, which takes bytes or an iterable of bytes. If an iterable is passed, the encrypted chunks will be lazily yielded without loading the entire data in memory. After yielding all the chunks, the decryption dictionary is the last yielded value.
- The preexisting `encrypt_attachment()` function is now a wrapper over `encrypted_attachment_generator()` and behaves the same as before (except for also accepting iterable of bytes).
- Added `nio.crypto.async_attachments.async_encrypt_attachment()`, which is an async version of `encrypted_attachment_generator()`. It accepts bytes, iterable of bytes, async iterable of bytes, path strings, `Path` objects, and opened binary file/aiofile objects as data.
- Added `encrypt` argument for …
=> Async lazy encryption for uploads

nio/rooms.py, tests/room_test.py
This changes the method (and subsequently the `MatrixRoom.display_name` property) to return `None`, instead of a hardcoded string that would make us have to jump through extra hoops to know if the room is actually empty or literally named "Empty room?".
=> MatrixRoom.group_name(): return None for empty rooms

nio/events/room_events.py, nio/schemas.py, tests/data/events/message_notice.json
This makes `RoomMessageNotice` a subclass of `RoomMessageFormatted`, since [`m.notice`](https://matrix.org/docs/spec/client_server/latest#m-notice) events can have `format` and `formatted_body` keys.
=> RoomMessageNotice: support format/formatted_body

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, tests/async_client_test.py, tests/client_test.py, tests/conftest_async.py
- Add missing `room_redact()` to the `AsyncClient`, addresses https://github.com/poljar/matrix-nio/issues/83
- Add docstring and test for the already existing `HttpClient.room_redact()`
- Make some docstrings in *async_client.py* more consistent ("Arguments: ..." *after* "Returns ...") 
- Set a max number of timeouts for `AsyncClient` from test fixtures, to avoid having tests just silently hanging forever if something goes wrong with a request 
- Fix deprecation warnings being issued if an `AsyncClientConfig` is passed, they should only appear if a `ClientConfig` is passed 
- Add a new `synced_client` fixture that returns an already logged-in and synced `HttpClient`, to avoid having to copy-paste a large chunk of code for every new http client test
=> Room redaction for AsyncClient and other improvements

nio/__init__.py, nio/client/__init__.py, nio/client/async_client.py, nio/crypto/async_attachments.py, nio/exceptions.py, nio/monitors.py, rtd-requirements.txt, setup.py, tests/async_attachment_test.py, tests/async_client_test.py
This adds a `TransferMonitor` class that users can instantiate and pass to `AsyncClient.upload()`. While the method is processing data chunks to send, it will suspend or cancel the processing if the monitor's attributes are set to do so. By leveraging aiohttp's `TraceConfig`, the monitor's `transferred` (bytes sent) property is updated, which are the basis for other provided statistics such as average speed or estimated remaining time. 
Pausing is currently not well supported across homeservers, with the connection timing out after a certain time depending of the HTTP server's config (for example, `client_body_timeout 300s;` in nginx). When this happens, the upload process has to restart from 0.
I plan to make `download()` also able to use the monitor later.
=> Uploads monitoring, pausing and cancelling

nio/client/base_client.py
Hey @poljar :wave: 
I was trying to run the tests for weechat-matrix and it looks like this is the only typing that's not Python2.7 compatible. Is 2.7 still officially supported? What I see in the README is that
> nio on the other hand works with older python versions as well.
Thanks for reviewing!
=> Use Py2.7 compatible typing for access_token

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, tests/async_client_test.py, tests/client_test.py
For some deployments of matrix.org (namely Citadel by Thalès) the provided methods do not allow to use the standard auth string. This commit for allowing logging in using a custom formed auth_string. 
I defined specific methods for logging in, rather than overloading the existing ones, but I find the overloading solution to be more elegant.
Please let me know if additional changes are required.
Signed-off-by: Benoît Clouet <benoit.clouet@gmail.com>
=> Add the ability to login using a custom auth string

nio/client/async_client.py, tests/async_client_test.py
The default transport used by `Connection` objects (which are returned by `ClientSession.connector.connect()`) has an inappropriate default write buffer limit ranging from 64 to 512KiB depending on the implementation (tested with normal asyncio and uvloop).
If the user's connection isn't fast enough to fill the buffer at least once per second, this causes the callback for the client's trace config `on_request_chunk_sent` to fire too fast without waiting for the server to actually receive chunks, and the `TransferMonitor` is left hanging at the end waiting for the server to catch up and buffers to be drained.
I haven't found a direct or clean way to change the transport buffer size in aiohttp, so I'm patching `connect()` to set it to 16KiB max.
=> Improve TransferMonitor statistics accuracy

nio/client/async_client.py
Adds an option for `AsyncClientConfig` to specify a timeout for aiohttp `ClientSession`  requests, defaulting to 30 seconds instead of 5 minutes.
`sync()` will override this using the `timeout` argument + 5 seconds (to give the server a chance to return normally).
This notably fixes an issue where `sync_forever()` seems to hang eternally after a machine wakes up from hibernation or network interface changes, even though a `timeout` argument value is passed.
`download()`, `thumbnail()` and `upload()` will ignore this and pass a timeout of 0 (no timeout), since we don't want to kill user download/uploads.
I'm not sure how to test these changes, aioresponse doesn't seem to have a way to simulate a server hanging.
=> Configurable AsyncClient request timeout 

nio/responses.py, tests/responses_test.py
A server could return something unexpected instead of an image, for example an HTML error page. In these cases we need to return a ThumbnailError.
=> ThumbnailResponse: ensure content type is image/*

nio/api.py, nio/client/async_client.py, tests/async_client_test.py
- `room_messages()`: add a `message_filter` parameter
- `sync()`, `sync_forever()`: `filter` can be `None`, dict *or* a filter ID
- `AsyncClient.sync_forever()`: Add a `first_sync_filter` parameter 
- `Api.sync()` docstring: document `full_state` parameter and add missing
spaces before some `(type)`s
- `AsyncClient.sync()` docstring: add missing space after `since`
- Convert comment type hints to Python 3.6+ style
=> Sync filter-related additions and fixes 

nio/api.py
The grammar for device IDs is not documented (matrix-org/matrix-doc#1257).  In the meantime we should not assume that device IDs will not contain reserved characters.
=> api: URI encode device_id in update_device

nio/rooms.py, tests/room_test.py
- Conform to the [r0.6.0 spec](https://matrix.org/docs/spec/client_server/r0.6.0#id342)
- Use the room summary to calculate group display names and avatars,
making it work properly with member lazy loading and smarter with
how many names to list vs how many "x others" to show
- Provide a `MatrixRoom.group_name_structure` property that returns a
`(is_empty, user_names, x_others)` tuple suitable for clients
that want to show custom strings from the data
- Support "Empty Room (was Alice, User2, ...)" - note that I used "had" instead of "was", I think it makes more sense ("Alice" wasn't a room but a user part of that room) and the spec allows custom forms
- Use the `users` list as fallback if the room doesn't have a `summary`, and raise the maximum of names listed vs "x others" to 5, to match …
=> Improve group rooms display name and avatar calculation

nio/events/ephemeral.py, nio/rooms.py, nio/schemas.py, tests/client_test.py, tests/data/events/receipt.json, tests/event_test.py, tests/room_test.py
Closes #111 
ReadReceiptEvent handles notifying the client when users change their
most recently read message.
@poljar We discussed on #nio:matrix.org storing receipts in the `Room`, but I wasn't sure exactly what you meant (and I figured people in the room might not appreciate continued discussion). I'm not concerned about merging this right away but I figured this way you can see what I have and we can talk about how to track read receipts events in `Room`s.
The `from_dict()` method is a bit hairy, but that's unfortunately part
of the spec.  "m.receipt" events have four parts; the `event_id`,
`receipt_type`, `user_id`, and timestamp.  There may be only a single
(`user_id`, `receipt_type`) pair associated with a single `event_id`,
but each "m.receipt" event can have multiple …
=> Adds ReadReceiptEvent for m.receipt events

nio/client/async_client.py, tests/async_client_test.py
For `upload()`, accept an optional `filesize` argument.
=> Add Content-Length to headers when uploading

nio/events/room_events.py, tests/data/events/power_levels.json, tests/event_test.py
Accept a `target_user_id` parameter to check if a user can kick or ban
another one, depending on if the user's power level >= minimum kick/ban
power level and > target's power level
=> Improve PowerLevels.can_user_kick/ban()

nio/client/async_client.py
- Check for `M_LIMIT_EXCEEDED` or `429` status code on response instead of
if the response has a set `retry_after_ms` attribute
- If it an error of this kind but `retry_after_ms` isn't set, default to `5000`
=> Catch "Too Many Requests" errors more reliably

nio/events/ephemeral.py, nio/schemas.py, tests/data/events/receipt_invalid.json, tests/event_test.py
Synapse pre-0.99.3 has a [bug](https://github.com/matrix-org/synapse/issues/4898) where timestamp values are sent as a JSON string instead of as an object. Since m.receipts can have a number of m.read receipts inside, we don't want to throw away the whole event just for a couple bad timestamps.
This commit makes the schema accept those bad values and then ignores them in the `ReceiptEvent.from_dict()` method.
=> Fix handling of m.receipts with invalid ts values

.gitignore, nio/client/async_client.py, tests/async_client_test.py
Affects #85 
Adds the `room_read_markers()` method to the AsyncClient, allowing users to set the fully_read position and (more importantly, imo) the read receipt position. This is almost exactly what was in place for `AsyncClient.room_typing()` but modified for read receipts. Tested working with Synapse 1.12.3.
This PR also modifies the .gitignore to ignore the build folder, because I keep building to test with Synapse and then git thinks I have 40+ files to commit...
=> Add room_read_markers() to AsyncClient

nio/responses.py
It's confusing when the to_device messages are not shown in the string
representation even though _SyncResponse() contains them.
=> _SyncResponse: display to_device events in __str__()

nio/api.py, nio/client/async_client.py, tests/async_client_test.py
As mentioned in #85.
Adds the `update_device()` method to the AsyncClient.
I also corrected the type hints for the `update_device()` method in api
First PR and new to python, i tried my best to include a test.
Feedback is more then welcome :)
=> Add update_device() to AsyncClient

nio/api.py, nio/client/async_client.py, tests/async_client_test.py
Affects #85
Adds the `login_info()` method to the AsyncClient.
I also changed the type hints for the `login_info()` method in api to python3 syntax
=> Add login_info() to AsyncClient

nio/responses.py, nio/rooms.py
- Update the room's summary with the new summary's joined/invited member
if that count isn't `None`, lets `0` be a valid new value
- Summary heroes can now be a list or `None`, the room's summary will be
updated if the new summary is a list (empty or not) but not if
it's `None`
=> Fix room summary update when new summary has falsy attributes

test-requirements.txt
These missing packages are required to run pytest.
=> Add missing test requirements

nio/api.py, nio/client/async_client.py, nio/client/base_client.py, nio/responses.py, tests/async_client_test.py
I´m trying to implement `room_get_event` - [Matrix Specs](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-rooms-roomid-event-eventid)
I got the api part.
But have a question to the `async_client` part. If i use `_send` it will call `receive_response` but i don´t think that´s what we want.
Ideally the method `async_client.room_get_event()` should return the requested event as EventObject or None?! if not_found?
=> Add room_get_event method to api

nio/client/base_client.py
Just a small typo fix in a user-visible warning: `encrytpion` -> `encryption`.
=> Fix typo in encryption warning

nio/client/async_client.py, tests/async_client_test.py, tests/data/sample_text_file.py
Closes #133.
Tracks Sync and Async files separately so that later, if required, we can handle those cases separately. At this point `upload()` doesn't require files to be opened in binary format but I believe `_send()` fails if the file is in a text format.
Tested uploading plain text files and images to Synapse.
=> Use file objects directly in upload()

nio/api.py, nio/client/async_client.py, nio/client/base_client.py, nio/events/__init__.py, nio/events/presence.py, nio/responses.py, nio/rooms.py, nio/schemas.py, tests/async_client_test.py, tests/client_test.py, tests/data/sync.json
Yesterday there was the question if nio supports presence/status in the nio matrix room.
So i did a thing :)
Add support for `m.presence` in sync events. [Spec](https://matrix.org/docs/spec/client_server/latest#m-presence)
Add support for PresenceEvent callbacks
Add `get_presence` and `set_presence` to async client
Add `presence`, `last_active_ago`, `currently_active` and `status_msg` fields to MatrixUser
=> Add presence support

nio/events/presence.py, nio/rooms.py
The `last_active_ago`, `currently_active` and `status_msg` keys are
optional in `parsed_dict`, fix `PresenceEvent` fields to reflect that
and some related type hints.
=> Fix PresenceEvent.from_dict() parsing

README.md, docker/Dockerfile, docker/README.md, docker/build_and_install_libolm.sh
This PR adds a docker image that can be used as a base for others using matrix-nio in their projects. It sets up an alpine environment with libolm and olm python3 bindings already installed.
Someone can then create another docker image on top which then installs their own necessary dependencies when shipping their project.
I'm hoping this will make matrix-nio-based projects easier to deploy, as the dependency on the libolm C library can be somewhat of a slight hindrance.
=> Add a docker container with e2ee deps pre-installed

nio/client/async_client.py, nio/client/base_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py
Because of https://github.com/matrix-org/matrix-doc/issues/2590 and https://github.com/matrix-org/synapse/pull/7606.
This PR takes the `user_id` of `get_presence` and passes it to the response class instead of taking it from the response data.
=> presence: Use user_id from request instead of response

doc/built-with-nio.rst
`delator` is basically just yet another bot, but it supports encrypted rooms and is actually easy to extend.
=> doc: add a project to the built-with-nio list

doc/built-with-nio.rst
`cody` is a REPL for your matrix rooms - built with nio
=> doc: add `cody` to the built-with-nio list

README.md
- adding this sentence can reduce installation time for many people and avoid frustrations
- I read all of https://gitlab.matrix.org/matrix-org/olm and then started to download libolm source code, compiled it, etc.I ran into an error, had to troubleshoot, etc. 
- I spend 2 hours, just to find out that I could have done it the easy way in 10 seconds with a simple dnf or apt-get. 
- It was just simply nowhere mentioned that these packages are available.
- I think adding this sentence would help a lot, and avoid other people unnecessarily doing what I did (compile the source)
=> added further sentence to ease installation

examples/restore_login.py
- no real change: just changing the order of 2 fields
- putting the access_token at the end makes the config/credentials file more readable
- imagine the user doing a `more` or `nano` on the file, the user_id was "hiding" behind access_token 
- now the fields are more easy to read, and nothing hides behind the long access_token
- an not one character more in the source file :)
- also I put the user_id before device_id, seems more natural, more top-down, now the complete ordering seems to be more top-down
=> made config file more readable

doc/examples.rst
In the first "attention"-box on the [example doc](https://matrix-nio.readthedocs.io/en/latest/examples.html) the pip install instruction is missing. Fixed this by inlining the command in the sentence above.
=> doc: fix hidden pip install command in examples

nio/crypto/sas.py
- Problem: reached assert in receive_mac_event()
- I wrote a client that performed emoji verification
- my client used a mix of AsyncClient and Sas methods 
(probably in an incorrect order)
- my client logged out and logged back in between the 3 events 
(KeyVerificationStart, KeyVerificationCancel, KeyVerificationKey)
- under these conditions (constant logout and login between 
events) I could trigger the assertion stmt 
(assert self.chosen_mac_method) in function receive_mac_event()
line 697 many times (about 100)
- it seems that I somehow got into the key_received state either 
without calling accept_verification (this is a usage error) or 
without receiving an m.key.verification.accept event.
- It was suggested to add a check that we are in the correct 
state (started or accepted) at …
=> sas: reached assert in receive_mac_event()

nio/api.py, nio/client/async_client.py, nio/client/http_client.py
A few places had capitalized even though the enum has lowercase keys.
=> Fix capitalization of RoomVisibility.Private in docstrings

examples/restore_login.py
- renamed to credentials.json
- 2 advantages
- consistency
- can be used across examples
- create here, then use later in verify_with_emoji.py for example
=> renamed to credentials.json

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py
https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-user-userid-filter
Also corrects the `room_messages()` methods to only accept filter dicts, using an ID with `/messages` is not supported by the spec and results in a server error.
=> Add support for uploading sync filters

nio/api.py, tests/api_test.py, tests/async_client_test.py, tests/client_test.py
This closes: #211 
This PR changes the `path` parameter of `_build_path` to List[str], improves a number of tests, and fixes at least one.
Previously, accepting `path` as a "str" caused a bug where valid matrix names (like "@a-z0-9._=-/:example.com") were breaking as the "/" was interpreted as a path separation.
The benefit of moving to a List[str] is that each substring of the path can be separetly percent-encoded and then combined into one long path string. The above username becomes "%40a-z0-9._%3D-%2F%3Aexample.com" and there is no confusion whether that is a name or a path.
=> (In-Progress) Percent encode User ID

nio/client/async_client.py, tests/async_client_test.py, tests/data/sync.json
PR #153 added account data support to base-client, but did not add the
needed changes to async-client's _handle_joined_rooms. Copy needed code
and tests form base-client to async-client.
=> async-client: Add support for account data.

nio/responses.py, nio/schemas.py
This tiny pull request changes parsing of SyncResponse such that when "device_lists" field is absent, it is substituted by the empty default. The sub-fields of "device_lists" are also supplied with empty defaults.
The spec says that "device_lists" is optional in the sync response (["End-to-End Encryption" -> "Protocol definitions" -> "Extensions to /sync"](https://matrix.org/docs/spec/client_server/r0.6.1#device-lists-sync)) My experience with dendrite is a bit more nuanced: I see `parsed_dict["device_lists"]["changed"]` present in the response, while `parsed_dict["device_lists"]["left"]` absent (which makes matrix-nio throw `KeyError`)
=> Treat "device_lists" in SyncResponse as optional.

nio/__init__.py, nio/api.py, nio/client/async_client.py, nio/client/base_client.py, nio/events/account_data.py, nio/events/room_events.py, nio/http.py, nio/responses.py, nio/rooms.py, nio/schemas.py, tests/async_client_test.py, tests/client_test.py, tests/data/events/power_levels.json, tests/data/events/push_rules.json, tests/data/events/to_flatten.json, tests/data/sync.json, tests/event_test.py, tests/http2_test.py, tests/room_test.py
As per:
https://matrix.org/docs/spec/client_server/latest#push-rules-events
https://matrix.org/docs/spec/client_server/latest#put-matrix-client-r0-pushrules-scope-kind-ruleid
https://matrix.org/docs/spec/client_server/latest#delete-matrix-client-r0-pushrules-scope-kind-ruleid
https://matrix.org/docs/spec/client_server/latest#put-matrix-client-r0-pushrules-scope-kind-ruleid-enabled
https://matrix.org/docs/spec/client_server/latest#put-matrix-client-r0-pushrules-scope-kind-ruleid-actions
=> Add support for push rules account data events and API

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, tests/api_test.py, tests/async_client_test.py
This is a fix for #238, to allow nio to access profile endpoints on a matrix server that requires authentication (in contrast with what the spec currently says). The new parameter follows the pattern `profile_get(user_id: str, access_token: str = None)`. AsyncClient and HttpClient will pass the access_token on to the profile Api module methods, if it has been set (or None if missing).
Missing from this pull requests, for which I'd be happy to get some input: testing for HttpClient. The async client uses aioresponse in its test suite, which makes it easy to make sure the client requested the right URI and give back appropriate response. Any suggestions for how to test the http client as well?
Fixes #238
=> Authenticated access to /profile endpoints

nio/api.py, nio/client/async_client.py, pyproject.toml
This changes provide support for SOCKS4(a) and SOCKS5 proxys as discussed in https://github.com/poljar/matrix-nio/issues/245. Because aiohttp only supports HTTP proxys this needs the new dependency [aiohttp-socks](https://github.com/romis2012/aiohttp-socks).
=> async_client: Support SOCKS proxys

nio/events/room_events.py, nio/schemas.py, tests/data/events/sticker.json, tests/event_test.py
~Closes #174~ Edit: Looks like I had misunderstood that issue. See discussion below
Adds the ability to have Sticker Events which currently give the 
1. body (which is like the tooltip)
2. URL (The mxc url to the image)
Feel free to let me know if I have missed out adding any more fields. 
And feel free to let me know if this PR covers everything that's required out of the issue this is closing.
=> Add Sticker events for Reactions

nio/schemas.py
This fixes compatibility issues for sync with dendrite. 
I can add additional defaults when testing with conduit.
=> schema: add defaults for compatibility with dendrite

nio/client/async_client.py
When you need to transform a bytearray to a readable interface the suggested one to use is BytesIO but the current type checking doesn't allow you to do so.
So I just added the BytesIO type to the list.
=> Support BytesIO streams for uploads

nio/crypto/olm_machine.py
This allows a custom store to return customized caches as well, for example a custom GroupSessionStore that only holds a single key per room id, sender key pair.
=> crypto: Always try to load the crypto data.

nio/crypto/attachments.py
Do not truncate the IV, but instead decode the initial counter value in the last 32bits and initialize the Counter correctly.
This fixes attachment decoding as produced by FluffyChat, and fixes https://github.com/poljar/weechat-matrix/issues/275
famedlysdk (used by FluffyChat) is using the following amendment to the matrix protocol, which changes the IV to be a full 128 bit counter block (padding + counter) when encrypting attachments: https://github.com/matrix-org/matrix-doc/pull/2492/files
After a discussion with Lukas Lihotzki (one of the authors of the famedlysdk), it seems that this change was discussed last year as not to waste half the entropy of the IV and should have been adopted by Element itself, but hasn't been done yet. Element still produces an IV with a zero counter, but it …
=> Initialize the whole counter block IV when decoding encrypted attachments

nio/schemas.py
This appears to allow the Weechat plugin to engage in E2EE conversations with new devices.
Fixes #263.
=> schemas: allow for devices in keys query that have no signatures

nio/responses.py
The `rooms` `join`, `invite` or `leave` objects can be absent in the sync response JSON. The `default` keyword used in the schema [will not fill missing values](http://json-schema.org/understanding-json-schema/reference/generic.html).
=> Fix parsing syncs missing invite/join/leave rooms

nio/api.py, nio/events/room_events.py, tests/event_test.py
`emxc://` URLs currently do not preserve mimetype information from the encrypted media message. Clients have to infer the mimetype with `file` or similar. This commit adds an optional `?mimetype` field to `emxc://` URLs to avoid client-side guessing.
=> Add media mimetype to emxc:// urls

nio/events/room_events.py
=> events: Allow the mimetype to be in the info for encrypted images

nio/api.py
This makes it possible to log in to a Conduit server.
According to [the spec](https://matrix.org/docs/spec/client_server/r0.6.1#identifier-types), `"user"` is deprecated in favor of `"identifier"`.
=> Use user identifier for login

nio/responses.py, nio/schemas.py
Makes the field `prev_batch` in `SyncResponse.rooms.join.timeline` optional. I have seen the field to actually be missing in sync responses generated by a recent Dendrite server.
This should close https://github.com/poljar/matrix-nio/issues/280
=> Make `prev_batch` in `room_timeline` optional.

nio/crypto/olm_machine.py, nio/schemas.py
This field has been deprecated for quite a while and is not used anymore
by Matrix clients. The Olm message index is instead embedded in the
serialized ratchet key format (since https://gitlab.matrix.org/matrix-org/olm/-/commit/e0b5197).
Also see https://github.com/matrix-org/matrix-doc/issues/1249#issuecomment-395358088.
=> Remove `chain_index` field when sending room keys.

.gitignore, pyproject.toml
The changes appear pretty simple: https://github.com/romis2012/aiohttp-socks/compare/v0.6.0...v0.7.1
This allows compatibility with python-socks 2.x. Tests all pass.
=> Update aiohttp-socks dependency

nio/client/async_client.py
According to [the spec](https://matrix.org/docs/spec/client_server/r0.6.1#id55), m.read events should send an empty object.
New Synapse versions seem more strict about this and ignore requests with `""` instead of `"{}"`.
=> Send empty object with m.read receipt

nio/events/account_data.py
We can not rely on Event having `room_id`. See [here](https://github.com/poljar/matrix-nio/blob/master/nio/events/room_events.py#L36).
Only encrypted events have `room_id`, so in unencrypted rooms you definitely need to use `room.room_id`.
And since room ids are case sensitive, `.lower()` should not be used in this case.
=> Add special check for "room_id" in PushEventMatch

pyproject.toml
jsonschema 4.4.0 requires python >=3.7, so python got an update, too.
As of 2021-12-23, python 3.6 has reached the end-of-life phase, see
https://www.python.org/dev/peps/pep-0494/#lifespan
=> Update jsonschema to version 4.4.0

nio/api.py, nio/client/async_client.py, nio/client/base_client.py, nio/client/http_client.py, nio/crypto/olm_machine.py, nio/crypto/sas.py, nio/event_builders/state_events.py, nio/events/misc.py, nio/events/room_events.py, nio/events/to_device.py, nio/http.py, nio/responses.py, nio/rooms.py, nio/store/database.py, nio/store/file_trustdb.py, tests/async_client_test.py, tests/client_test.py, tests/encryption_test.py, tests/event_test.py, tests/helpers.py, tests/sas_test.py, tests/store_test.py
Used `flynt` for most of the cases. Around 60 instances required manual conversion.
Fixes #314.
=> style: Convert from `str.format` to f-strings.

nio/client/async_client.py, tests/async_client_test.py
Also deprecate `server_name` and `media_id`.
Fixes #94.
=> feat: Add mxc URI parameter to `AsyncClient.download`.

docker/Dockerfile
This just raises the default versions of dependent software projects to their current versions.
When I built the bindings, I got confused why they weren't used. Turns out that my target container was already running Python 3.9 and not using the Python 3.8 package.
Alternative:
Do nothing. the Docker image allows you to change all these versions with `ARG`s.
=> Update Dockerfile: Update version numbers

doc/built-with-nio.rst
Hi,
Thanks a lot for this fantastic project !
I've build a simple webhook server with it: https://github.com/nim65s/matrix-webhook, and I guess it can be added in the docs.
=> doc: add matrix-webhook to built-with-nio

nio/responses.py
Got the following error while using this library against Conduit homeserver. Conduit does not add empty objects to the sent json and I interpret the matrix documentation as most field are optional and Conduit is not doing anything wrong in this case.
```python3
Traceback (most recent call last):
File "/config/custom_components/matrix_fix/__init__.py", line 193, in handle_startup
await self._client.sync_forever(timeout=30_000, loop_sleep_time=1_000)  # milliseconds.
File "/usr/local/lib/python3.10/site-packages/nio/client/async_client.py", line 1199, in sync_forever
await self.run_response_callbacks([await response])
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
return f.result()  # May raise f.exception().
File …
```
=> Parse room attributes more carefully

nio/schemas.py
Default "room.default=False" due to https://github.com/matrix-org/synapse/issues/13837
Fixes #348
=> Relax m.push_rules "room.default" event validation

nio/client/async_client.py, tests/async_client_test.py
This PR fixes the compatibility issues with python 3.11, which drops the support for (asyncio.coroutine)[https://docs.python.org/3/whatsnew/3.11.html#removed].
Also the test on buffer limits is skipped for python 3.11 due to a [CPython bug](https://github.com/python/cpython/issues/99277)
=> Fix python3.11 compatibility and tests

pyproject.toml
Partial motivation for this PR is to fix some downstream dependency resolution caused by poetry's `^` operator: e.g. `h11` `0.14.0` is not considered in range by `pip`  based on `h11 = "^0.12.0"`.
Project in question:
https://github.com/home-assistant/core/actions/runs/3581883765/jobs/6025559741
Getting to use `matrix-nio` in such a big project like `home-assistant` would be *huge*, so I'd really like to do whatever I can to get these two projects to play nicely :)
The `aiohttp` bump looks big, but it's only two releases apart: https://pypi.org/project/aiofiles/#history
=> Bump various dependencies

nio/client/async_client.py, tests/async_client_test.py
When calling either `sync` or `sync_forever` methods without passing the
`timeout` parameter, the value used for requests timeout is supposed to
be read from the client config.
While this value is correctly passed to the `ClientSession`, it is not
included as a parameter in the URL of the `/sync` API call at all,
making call return immediately, often with an empty response.
This change makes the API call use the `config.request_timeout` value
instead if no timeout was explicitely set.
=> Default to the configured request timeout when syncing

nio/client/async_client.py
This patch makes the `first_sync_filter` parameter of `AsyncClient.sync_forever` behave as described in the docstring.
Before this change, omitting the `first_sync_filter` parameter (or setting it to `None`) would cause the first sync call to not use a sync filter at all instead of using the sync filter specified in the `sync_filter` parameter.
I have tested this patch in my project.
=> Fix first_sync_filter parameter of AsyncClient.sync_forever

nio/crypto/olm_machine.py
When trying to import files from an Element backup, some of the exported keys are missing the "sender_claimed_keys" dictionary key. These entries in the encrypted file have the following shape:
```
{
'sender_key': '... ~256 bytes ...',
'room_id': '!room:homeserver',
'session_id': '... ~256 bytes ...',
'session_key': '... long value ...',
'forwarding_curve25519_key_chain': [],
'org.matrix.msc3061.shared_history': False,
'algorithm': 'm.megolm.v1.aes-sha2'
}
```
As a result, importing the whole file fails because of the schema validation for `Schemas.megolm_key_import`. This patch silently continues, but warns the user that some of the keys in the file weren't decrypted. I'm not familiar enough with the details of megolm; but this patch correctly works around this issue, instead of hard …
=> fix: Element exports keys without required fields

nio/client/async_client.py, nio/client/base_client.py, tests/async_client_test.py
`unitest.mock`'s `AsyncMock` tries to match the return value of method calls based upon async vs non-async when a `spec` is defined. The `client.base_client.logged_in` decorator is non-async and throws off `AsyncMock` making it return non-async `MagicMock`s for all method calls.
This PR duplicates the `logged_in` decorator with an async version.
=> make it easier to mock AsyncClient by matching `logged_in` decorator to async vs non-async

.pre-commit-config.yaml
checked in version of `black` conflicts with some version of `click`.  
```
Fix End of Files.........................................................Passed                                                                                                                                                                                                                                                                                                                               
Trim Trailing Whitespace.................................................Passed …
```
=> upgrade pre-commit's black version to 22.3.0

tox.ini
As of tox 4, passenv can no longer use space as a separator. This change uses a syntax valid in both tox 3 and 4.
See https://tox.wiki/en/4.2.2/upgrading.html#changed-ini-rules for more details.
=> Fix build failure caused by tox 4

nio/client/async_client.py
`AsyncClient.upload()` also supports passing file-like objects but the type hint didn't indicate that. So I corrected it.
Otherwise in PyCharm, passing a file-like object will emit type errors like this:
> Expected type '(int, int) -> str | Path | bytes | Iterable[bytes] | AsyncIterable[bytes] | BufferedIOBase | AsyncBufferedReader', got 'BytesIO' instead
=> Update type hints

nio/responses.py
This small change adds `WhoamiResponse` and `WhoamiError` into the `__all__` variable of `responses.py`.
This helps users to check if `AsyncClient.whoami` has returned an error or a success. Closes https://github.com/poljar/matrix-nio/issues/391.
=> Export Whoami{Response,Error} from responses.py.

tox.ini
Notice that in previous, otherwise-successful runs, the test coverage is 0%.
This should fix that.
=> Fix test coverage

nio/client/async_client.py, nio/client/base_client.py, tests/async_client_test.py, tests/client_test.py
Initially, `execute_callback` took one `room` argument, which was a `MatrixRoom`. Methods like `room_send` need the `room_id` to be a string to get it from `AsyncClient.rooms`. Since the `room_id` was a `MatrixRoom`, a `KeyError` was raised.
=> Fixed bug in Event Callbacks

pyproject.toml, rtd-requirements.txt
`python3.7` will no longer receive security updates after June 27, 2023.
We should no longer continue to actively support it nor develop in a backwards-compatible manner for it.
https://devguide.python.org/versions/
=> Drop support for EOL `python3.7`

nio/events/room_events.py, nio/rooms.py, nio/schemas.py, tests/room_test.py
Add support to handle `m.space.parent` and `m.space.child`, also add support for getting the parent / children in `MatrixRoom`.
Closes #371
=> Support m.space.parent and m.space.child events

.readthedocs.yaml 
This PR fixes #424 by adding a `.readthedocs.yaml` file
=> Add .readthedocs.yaml to support ReadTheDocs migration

contrib/archlinux/pkgbuild/PKGBUILD.git, nio/crypto/sas.py, pyproject.toml, rtd-requirements.txt
The project already requires Python 3.8 or newer. There is no reason to keep the `future` dependency any longer.
This will be necessary to provide support for Python 3.12, as `future` doesn't seem to be updated any longer and the current version will be incompatible with 3.12. https://github.com/PythonCharmers/python-future/issues/246
https://github.com/poljar/matrix-nio/blob/5354a4d5c03b9b85f36f0b8e5c153a6fe5dec8f9/pyproject.toml#L19
```
venv/lib/python3.11/site-packages/future/standard_library/__init__.py:65
/.../venv/lib/python3.11/site-packages/future/standard_library/__init__.py:65: DeprecationWarning:
the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
import imp
```
Fixes #435
=> Remove future dependency

nio/schemas.py, pyproject.toml
Fix deprecation from `jsonschema>=4.14.0`.
https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst#v4140
```
nio/schemas.py:49
/.../matrix-nio/nio/schemas.py:49: DeprecationWarning:
FormatChecker.cls_checks is deprecated. Call FormatChecker.checks on a specific FormatChecker instance instead.
@FormatChecker.cls_checks("user_id", ValueError)
nio/schemas.py:60
/.../matrix-nio/nio/schemas.py:60: DeprecationWarning:
FormatChecker.cls_checks is deprecated. Call FormatChecker.checks on a specific FormatChecker instance instead.
@FormatChecker.cls_checks("http_url", ValueError)
```
=> Fix jsonschema deprecations

nio/client/http_client.py
The `cgi` module is deprecated and scheduled for removal in Python 3.13.
https://docs.python.org/3.11/library/cgi.html#cgi.parse_header
```
nio/client/http_client.py:17
/Users/marc/Develop/05_one-time/matrix-nio/nio/client/http_client.py:17: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
import cgi
```
=> Replace cgi.parse_header()

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py, tests/data/get_hierarchy_response.json, tests/responses_test.py
Adds the ability to request a space's hierarchy as described in the [Matrix spec](https://spec.matrix.org/latest/client-server-api/#discovering-rooms-within-spaces). I've also written some tests around using the new method.
In addition to the change above, I added a way to run the linters (isort & black) so that you can simply run `make lint` and it'll run both of them.
=> Adds Space Hierarchy Request

nio/api.py, nio/client/async_client.py, nio/responses.py, nio/schemas.py, tests/async_client_test.py, tests/data/register_interactive_response.json, tests/responses_test.py
This pull request introduces functionality for token-authenticated registration in accordance with the [Matrix spec](https://spec.matrix.org/latest/client-server-api/#token-authenticated-registration). The changes cater to registration scenarios where a Matrix server requires a registration token and a session token, facilitating an interactive registration flow.
**Interactive Registration**: Introduced a register_interactive method. This method supports registering with a custom auth dictionary, adhering to the [specifications outlined by Matrix](https://spec.matrix.org/latest/client-server-api/#post_matrixclientv3register).
**Session Token in Standard Registration**: The conventional register method has been extended to accept an optional session_token. This modification ensures that …
=> Support for Token-Authenticated Registration

nio/api.py, nio/client/async_client.py, nio/client/http_client.py, nio/events/room_events.py, nio/rooms.py, nio/schemas.py, tests/async_client_test.py, tests/data/events/create_typed.json, tests/event_test.py
I added a `room_type` argument to `Api.room_create` to allow for the creation of rooms with a custom `type`.
The tests pass however I have not tested my changes in the wild yet.
=> Add room_type to room_create API function to allow for custom room types

nio/events/room_events.py, nio/schemas.py, tests/data/events/reaction.json, tests/event_test.py
Closes https://github.com/poljar/matrix-nio/issues/174
Adds a `ReactionEvent` with the fields `reacts_to` which gives the `event_id` of the message it reacts to and `key` which stores the reaction (most of the times an emoji but could be any string afaik).
=> add support for m.reaction events

doc/built-with-nio.rst
The description, and link, on the built-with-nio.rst page are both outdated, with the latter also being a dead link (I changed my username - it still works, but that's only because I parked the old one).
It would be nice to get this updated to properly reflect the state of the library, and also refresh the link.
If the description is too long or there's an issue with the link being to PyPi instead of a GitHub repository let me know and I can work something out.
=> [docs] Update the nio-bot description

nio/api.py, nio/client/async_client.py, nio/responses.py, tests/async_client_test.py
This PR aims to introduce the changes needed to implement & close #421, by calling the account_data/m.direct endpoint and returning a list of DM rooms.
From the [matrix spec](https://spec.matrix.org/v1.8/client-server-api/#mdirect), `m.direct` holds:
> A map of which rooms are considered ‘direct’ rooms for specific users is kept in account_data in an event of type m.direct. The content of this event is an object where the keys are the user IDs and values are lists of room ID strings of the ‘direct’ rooms for that user ID.
Using this endpoint should allow for a clear distinction between traditional rooms and rooms that've been flagged as "direct", without needing to use hacky workarounds like [checking for the optional `is_direct` in Invite …
=> Introduce the DM room account data (`m.direct`)

nio/events/room_events.py, nio/schemas.py, tests/event_test.py
[m.room.avatar](https://spec.matrix.org/v1.8/client-server-api/#mroomavatar) doesn't require `url`, and [m.room.canonical_alias](https://spec.matrix.org/v1.8/client-server-api/#mroomcanonical_alias) can have `alias` be null
=> Fix schemas for m.room.avatar and m.room.canonical_alias

nio/api.py, nio/client/async_client.py, tests/async_client_test.py
See: https://github.com/poljar/matrix-nio/issues/469
* MSC3567 allows an empty start param when getting messages via `room_messages`. This works fine against synapse but the nio library does not allow it. Added a test to ensure nio allows MSC3567
* Also fixed type hints for `update_receipt_marker`
Let me know if you want me to make any changes to conform to contributing guidelines or testing best practices
=> Changing room_messages to conform to MSC3567 + fixing type hints on update_receipt_marker

nio/schemas.py
Source: https://spec.matrix.org/v1.9/client-server-api/#get_matrixclientv3roomsroomidjoined_members
Note that it's not required.
This was encountered in the wild on the conduit.rs implementation.
Credit to @CobaltCause from conduit.rs to accompany me on this journey.
=> fix(spec): `display_name` is not a required property on `joined_members`

nio/responses.py, nio/schemas.py
Sources:
- https://spec.matrix.org/v1.9/client-server-api/#post_matrixclientv3keysclaim
- https://spec.matrix.org/v1.9/client-server-api/#post_matrixclientv3keysquery
Notice that "Required" is not here for `failures`.
This was encountered in the wild with conduit.rs implementation.
Credit to @CobaltCause for accompanying me on this journey.
=> fix(spec): `failures` is not a required property for E2EE APIs

nio/responses.py, nio/schemas.py
As per https://spec.matrix.org/v1.1/client-server-api/#get_matrixclientv3roomsroomidcontexteventid.
No field is required, we still keep `event` required because it happens to be the true required one.
Seen in the wild with conduit.rs.
=> fix(spec): `RoomContext` has no required field theoretically

nio/client/async_client.py, nio/client/base_client.py
I've moved the execution loops of callbacks to separate methods. This is so that the behaviour can be containedly redefined without needing to hard-rewrite all surrounding logic. As it is now, subclassing the client and adding functionality on running the callbacks would entail needing to keep an eye out for any changes to these whole methods upstream, lest an update be missed and either break it or simply not benefit from patches or upgrades to the flow.
=> Moved callback execution to separate methods.

nio/client/async_client.py
Should, fingers crossed, close #432.
This has been tested using the bot used to repro the original issue.
---
The issue came from the fact that, even after knowing the response content was expected to be application/json, it was *parsed* - `from_dict` then expected bytes or a path for the real content, however it received a json object (be that dictionary, array, integer, null, string, so on).
If it was given a dictionary, it'd assume it was an error response from the homeserver, and naively treat it as such.
If it was given anything else, it'd become confused and return an "invalid data" error.
This patch fixes this by simply __not parsing__ the response (as, from what I can tell, its not supposed to be parsed in this situation).
Edits, fixes, and changes welcome.
=> Fix #432 - Properly pass JSON content to DownloadResponse

nio/client/async_client.py, tests/async_client_test.py
This change adds a method to request that `sync_forever` main loop exits gracefully.
Examples use `Task.cancel` for this purpose, but I am concerned that canceling an async task may result in an inconsistent state, especially with anything concerning encryption. Using the new method will ensure that the latest sync response is fully processed by our `AsyncClient` before the sync loop exits.
=> Add `stop_sync_forever` method, to gracefully exit `sync_forever` loop.

src/nio/api.py, src/nio/client/async_client.py, src/nio/client/http_client.py, tests/async_client_test.py, tests/client_test.py
This was actually quite simple to implement lol.
Needs some real world testing ideally, but CI should be fine
Closes #517. **This change is incompatible with any homeservers that do not implement matrix v1.11** (however, those same homeservers also can no longer access most media anyway)
Closes #511. Current behavior involves stripping the access token from the query parameters outright in favor of using the `Authorization` header. This change will not break any homeservers that are matrix v1.1 compliant.
=> Use authenticated media + Authorization header

.gitignore, src/nio/api.py, tests/async_client_test.py
Media uploads still make use of `/_matrix/media/v3/upload`, and this was not caught before #520 was merged, meaning that as of nio 0.25.1, media uploads cannot be performed.
This change simply reverts part of 520 by replacing the upload build_path call with the old media endpoint.
=> (fix #520) utilise the old media path for uploads

src/nio/events/room_events.py, src/nio/schemas.py, tests/data/events/call_answer.json, tests/data/events/call_answer_legacy.json, tests/data/events/call_candidates_legacy.json, tests/data/events/call_hangup_legacy.json, tests/data/events/call_invite.json, tests/data/events/call_invite_legacy.json, tests/event_test.py
Currently, the schema of the call events specifies the field "version" as integer. The matrix specification [1] lists the type of the field as string. Also, receiving and handling call events does not work (see also issue #347) and results in the following log messages:
WARNI Error validating event: '1' is not of type 'integer'
Failed validating 'type' in
schema['properties']['content']['properties']['version']:
{'type': 'integer'}
On instance['content']['version']:
'1'
To fix this issue, change the type from integer to string and update the tests accordingly.
[1]: https://spec.matrix.org/v1.11/client-server-api/#common-fields
=> Fix type of call event version

doc/conf.py, pyproject.toml
> `m2r2` is a fork of `m2r` and both are more or less unmaintained. This replaces it by `sphinx_mdinclude` which is maintained.
=> Replace m2r2 by sphinx_mdinclude
